language:  dart

addons:
  apt:
    packages:
      - lib32stdc++6

env:
    - PROJECT="basic_interaction" 
    - PROJECT="drawer_navigation"
    - PROJECT="mvvm" 
    - PROJECT="money"
    - PROJECT="ui_testing"

install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor

script:
    - cd $PROJECT
    - ../flutter/bin/flutter test    
    - cd ..

cache:
  directories:
    - $HOME/.pub-cache