language:  dart

addons:
  apt:
    packages:
      - lib32stdc++6

env:
    - PROJECT="async_recipe"
    - PROJECT="basic_interaction"
    - PROJECT="drawer_navigation"
    - PROJECT="empty_app"
    - PROJECT="hello_world"
    - PROJECT="hello_world_custom"
    - PROJECT="hello_world_themed"
    - PROJECT="launch_url"
    - PROJECT="license"
    - PROJECT="list"
    - PROJECT="minimal_clean_arch"
    - PROJECT="money"
    - PROJECT="mvvm"
    - PROJECT="picker"
    - PROJECT="placeholder_posts"
    - PROJECT="properties"
    - PROJECT="rest"
    - PROJECT="scoped_model_recipe"
    - PROJECT="settings"
    - PROJECT="ui_testing"
    - PROJECT="ultimate_answer"
    - PROJECT="webview"

install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor

script:
    - cd $PROJECT
    - ../flutter/bin/flutter test    
    - | 
      if [[ -d "core" ]]
      then 
        cd core
        ../../flutter/bin/flutter test    
        cd ..
      fi  
    - | 
      if [[ -d "infrastructure" ]]
      then 
        cd infrastructure
        ../../flutter/bin/flutter test    
        cd ..
      fi  
    - cd ..

cache:
  directories:
    - $HOME/.pub-cache